---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Move files
  template:
    src: "/home/web/*"
    dest: "~/web/"

- name: Executing node
  shell: |
    pm2 start ~/web/main.js -f