---
- name: Build Package
  shell: |
    cd ~/project/backend
    sudo npm install
    sudo npm run build   

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "./dist"
    dest: "~/web"

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f