---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "~/project/backend/dist"
    dest: "~/web"

- name: Executing node
  shell: |
    pm2 start ~/web/main.js -f